### ISSUE TITLE
Package Relay / V3 package RBF deployment

### ISSUE THREAD

**Issue by instagibbs** [bitcoin-inquisition/bitcoin#11]
i.e. port https://github.com/bitcoin/bitcoin/pull/25038

and implementation of https://github.com/bitcoin/bips/pull/1382

**Comment by maflcko** [comment]
I guess this can be closed, because it is included in https://github.com/bitcoin-inquisition/bitcoin/releases/tag/v28.0-inq now?

**Comment by instagibbs** [comment]
completed
