### ISSUE TITLE
Epehemeral Anchors deployment

### ISSUE THREAD

**Issue by instagibbs** [bitcoin-inquisition/bitcoin#12]
On top of https://github.com/bitcoin-inquisition/bitcoin/issues/11

i.e. port https://github.com/bitcoin/bitcoin/pull/26403

**Comment by ajtowns** [comment]
Does it make sense to mark this as complete, and perhaps open a new one for the extra features pkg relay will enable if/when pkg relay is available?

**Comment by instagibbs** [comment]
SGTM
