### ISSUE TITLE
Inquisition branding/versioning

### ISSUE THREAD

**Issue by ajtowns** [bitcoin-inquisition/bitcoin#20]
Should we do more "branding" changes here?

 * README updates? (cf [knots](https://github.com/bitcoinknots/bitcoin/commit/51dda98f456acce9473349e29b9f08a2338cc2e2))
 * announce inquisition via the subversion (cf [knots](https://github.com/bitcoinknots/bitcoin/commit/444c641436e6f7e13b8a82e03f33592e47c571ae))
 * other changes?

**Comment by michaelfolkson** [comment]
Longer term I think the more important thing is establishing guidelines for when soft fork proposals can be added to bitcoin-inquisition. I'm already starting to lose track on the status of various soft fork proposals being enabled on bitcoin-inquisition. A benevolent dictator (AJ, AJ and Kalle?) maintainer model seems fine to me but even with that some guidelines and some prerequisites would prevent AJ from being hounded to merge weak and/or unfinished proposals. It is less of a concern than on mainnet (especially with custom signets available) but over time this is going to get harder and harder to manage effectively.

**Comment by ariard** [comment]
On branding, "bitcoin-inquisition" hats and hoodies :)

**Comment by ajtowns** [comment]
I guess one question "announce inquisition via the subversion" might help answering is "how do I know if my node is connected to any peers running inquisition, so that txs that use new features have any chance of propagating and getting mined?"

**Comment by ajtowns** [comment]
See #36
