### ISSUE TITLE
Branch for easy rebase to master

### ISSUE THREAD

**Issue by levantah** [bitcoin-inquisition/bitcoin#61]
### Please describe the feature you'd like to see added.

Maybe I'm missing some Git magic — please teach me if so.

I think it would be great to have a clean branch (i.e. without stable-branch-related commits like bitcoin/bitcoin@fccd32efe6e2950b2c74fdec2ade54040ca32a2c) for ease rebase to Bitcoin master (including the disabling of mainnet and testnet).

### Describe the solution you'd like

With `inq` as this repo's git remote and `origin` as bitcoin/bitcoin, one can easily do following:

```sh
$ git checkout v27.0-inq
$ git switch -c myinq # git checkout -B myinq
$ git rebase origin/27.x
```

### Describe any alternatives you've considered

Rebase to origin/master of bitcoin/bitcoin repo fails.

### Please leave any additional context

```sh
$ git remote -v show
inq	https://github.com/bitcoin-inquisition/bitcoin (fetch)
inq	https://github.com/bitcoin-inquisition/bitcoin (push)
origin	https://github.com/bitcoin/bitcoin (fetch)
origin	https://github.com/bitcoin/bitcoin (push)
```

**Comment by maflcko** [comment]
> Rebase to origin/master of bitcoin/bitcoin repo fails.

This is normally expected, because many changes happened in the origin upstream development branch to prevent the automated rebase. You'll have to manually rebase the changes, but this is normally difficult for consensus code changes.

**Comment by levantah** [comment]
Thanks.
