### ISSUE TITLE
Transactions containing OP_CAT don't get mined anymore.

### ISSUE THREAD

**Issue by msinkec** [bitcoin-inquisition/bitcoin#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Recently, my transactions containing OP_CAT stopped getting mined to singet. They used to work before. Now, they still get accepted by my local inquisition node, but they never end up in a block.

Here's an example serialized txn: https://pastebin.com/rg3SEnDQ

I've got the following relay nodes in my config:
[signet]
addnode=http://inquisition.bitcoin-signet.net 
addnode=http://inquisition.taprootwizards.com

### Expected behaviour

\/

### Steps to reproduce

\/

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

25.2 and 27.0

### Operating system and version

generic Linux

**Comment by arminsabouri** [comment]
Is it possible your fee is not competitive. Blocks on signet regularly contain spends that use OP_CAT.

**Comment by ajtowns** [comment]
There was a big backlog on signet around June 19th, at around block [200634](https://mempool.space/signet/block/000000261a83e9a7b77b8b34a37967de8749050729d5b58d6013390aa99e6364).
